In [1]:
import numpy as np

empty_arr = np.empty ((3,3))
print(empty_arr)

full_arr = np.full ((3,3) , 15)
print(full_arr)

[[1.67656e-316 0.00000e+000 0.00000e+000]
 [0.00000e+000 0.00000e+000 0.00000e+000]
 [0.00000e+000 0.00000e+000 0.00000e+000]]
[[15 15 15]
 [15 15 15]
 [15 15 15]]
