1.Create an empty and a full numPy array

In [7]:
import numpy as np

#Empty Array :
empty_arr = np.empty((4,3) , dtype = int)
print(empty_arr)

#Full Array:
full_arr = np.full([3,3] , 10 , dtype=int)
print(full_arr)

[[20808512        0        0]
 [       0        0        0]
 [       0        0        0]
 [       0        0        0]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
